version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: carwash-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=carwash_db
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/postgres_data
  
volumes:
  postgres_data: